# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

# flag makes all dependencies build as frameworks
use_frameworks!

target 'BlogReader', :exclusive => true do
    
    pod 'Typhoon', :head
    pod 'CKUITools'
    pod 'ICLoader'
    pod 'NGAParallaxMotion'
    pod 'NSURL+QueryDictionary'
    pod 'OCLogTemplate'
    pod 'PaperFold', :git => 'https://github.com/jasperblues/PaperFold-for-iOS.git', :tag => '1.2-no-gesture-recognizers'
    pod 'PromiseKit/Swift', :git => 'https://github.com/mxcl/PromiseKit.git', :branch => 'swift-1.2'

end

target 'BlogReaderTests' do

end


inhibit_all_warnings!
